#!/bin/bash

# Start the container.
if [ ! $# -gt 0 ]; then
  # First compile our configuration files for this container.
  /usr/local/bin/confd -onetime

  # Start our supervisor process to begin serving data.
  /usr/local/bin/supervisord -c /etc/supervisord.conf -n
else
  exec "$@"
fi
